[package]
name = "nn-core"
version = "0.1.0"
edition = "2024"
description = "MoE Transformer core implementation"
license = "CC-BY-NC-4.0"

autobenches = false

[[bin]]
name = "bench"
path = "benches/bench.rs"

[[bin]]
name = "convergence"
path = "src/bin/convergence.rs"

[[bin]]
name = "convergence_gpu"
path = "src/bin/convergence_gpu.rs"
required-features = ["metal"]

[features]
default = ["cpu"]
cpu = []
metal = []

[dependencies]
libc = "0.2"

[build-dependencies]
cc = "1"
